//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkConcepts
{
    using System;
    using System.Collections.Generic;
    
    public partial class claimHeader
    {
        public int claimheaderid { get; set; }
        public string claimreference { get; set; }
    
        public virtual header header { get; set; }
    }
}
